In [ ]:
import numpy as np

prob_sunny = 1.0
prob_rainy = 0.0
print(prob_sunny, prob_rainy)
for i in range(10):
    next_sunny = prob_sunny * 0.9 + prob_rainy * 0.5
    next_rainy = prob_sunny * 0.1 + prob_rainy * 0.5
    prob_sunny, prob_rainy = next_sunny, next_rainy
    print(prob_sunny, prob_rainy)


probs = np.array([1, 0])
transition_matrix = np.matrix([[0.9, 0.1], [0.5, 0.5]])
print(transition_matrix)
print(probs)
for i in range(10):
    probs = probs * transition_matrix
    print(probs)

print(np.linalg.eig(np.transpose(transition_matrix)))

1.0 0.0
0.9 0.1
0.8600000000000001 0.14
0.8440000000000001 0.15600000000000003
0.8376000000000001 0.16240000000000004
0.8350400000000002 0.16496000000000005
0.8340160000000002 0.16598400000000005
0.8336064000000003 0.16639360000000003
0.8334425600000004 0.16655744000000006
0.8333770240000004 0.1666229760000001
0.8333508096000004 0.1666491904000001
[[0.9 0.1]
 [0.5 0.5]]
[1 0]
[[0.9 0.1]]
[[0.86 0.14]]
[[0.844 0.156]]
[[0.8376 0.1624]]
[[0.83504 0.16496]]
[[0.834016 0.165984]]
[[0.8336064 0.1663936]]
[[0.83344256 0.16655744]]
[[0.83337702 0.16662298]]
[[0.83335081 0.16664919]]
(array([1. , 0.4]), matrix([[ 0.98058068, -0.70710678],
        [ 0.19611614,  0.70710678]]))
