# Absorbing Markov Chains
[Absorbing Markov Chains](https://en.wikipedia.org/wiki/Absorbing_Markov_chain) are markov processes where each state has a path or a way to achieve an absorbing state. That is the overall probabilities

# Drunkards Walk
Let's take an example where, we have a drunk man. Let's say that he is walking home in a straight line. At position 0 there is his home. At position 3 there is the bar. If he ends up at either home or his bar he will stay there. For any position in between 0 and 3, (1 or 2) there is a 50 percent chance that they increase position by 1 and 50 percent chance they decrease their position by 1. He will never stay at position 1 or 2 for more than 2 rounds.

Let's take what we have learned from Markov Processes and build a matrix.

$$
\begin{align*}
\begin{pmatrix}
1 & 0 & 0 & 0\\
1/2 & 0 & 1/2 & 0\\
0 & 1/2 & 0 & 1/2\\
0 & 0 & 0 & 1
\end{pmatrix}
\end{align*}
$$

This matrix represents the transition matrix between the 4 positons or states. Now we want to change this into canonical form where all of the absorbing states are on the bottom right. This gives us some nice properties

$$
\begin{align*}
\begin{pmatrix}
0 & 1/2 & 1/2 & 0\\
1/2& 0 & 0 & 1/2\\
0 & 0 & 1 & 0\\
0 & 0 & 0 & 1
\end{pmatrix}\\
\end{align*}
$$

We can abstract and generalize this format to be the following $A = \begin{pmatrix}
Q & R \\
0 & I
\end{pmatrix}$ Where Q is the probability of moving between non-terminal states, R is the probability that we transition to a terminal state and $I$ is the identity matrix.

The wikipedia page for Absorbing Markov chains has a great explanation of how we can use this property to solve problems.

In [9]:
import numpy as np
from numpy.linalg import inv

In [2]:
transition = [[0, 0.5, 0.5, 0],
 [0.5, 0, 0, 0.5],
 [0, 0, 1, 0],
 [0, 0, 0, 1]
 ]
transition_matrix = np.matrix(transition)

In [6]:
for i in range(8):
    num_turns = 10**i
    print(f"num_turns = {num_turns}")
    print(transition_matrix**num_turns)

num_turns = 1
[[0.  0.5 0.5 0. ]
 [0.5 0.  0.  0.5]
 [0.  0.  1.  0. ]
 [0.  0.  0.  1. ]]
num_turns = 10
[[9.76562500e-04 0.00000000e+00 6.66015625e-01 3.33007812e-01]
 [0.00000000e+00 9.76562500e-04 3.33007812e-01 6.66015625e-01]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+00]]
num_turns = 100
[[7.88860905e-31 0.00000000e+00 6.66666667e-01 3.33333333e-01]
 [0.00000000e+00 7.88860905e-31 3.33333333e-01 6.66666667e-01]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+00]]
num_turns = 1000
[[9.33263619e-302 0.00000000e+000 6.66666667e-001 3.33333333e-001]
 [0.00000000e+000 9.33263619e-302 3.33333333e-001 6.66666667e-001]
 [0.00000000e+000 0.00000000e+000 1.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 1.00000000e+000]]
num_turns = 10000
[[0.         0.         0.66666667 0.33333333]
 [0.         0.      

In [11]:
Q = [[0, 0.5], [0.5,0]]
R = [[0.5, 0],[0, 0.5]]
I = np.identity(2)
N = I-Q
print(inv(N)*R)


[[0.66666667 0.        ]
 [0.         0.66666667]]
[[0.66666667 0.        ]
 [0.         0.66666667]]
